sudo: required
services:
  - docker

jobs:
  include:
    - stage: test
      env: Type='bindgen test'
      script:
        - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw intelhpdd/libzfs
        - docker exec -i libzfs bash -c 'cd /rust-libzfs/node-libzfs && cargo build'
        - docker exec -i libzfs bash -c 'cd /rust-libzfs/libzfs-sys && cargo test bindgen_test_layout'
    - stage: test
      env: Type='virus scan'
      script:
        - sudo apt-get install clamav -y
        - sudo freshclam
        - clamscan --quiet -r ./
    - stage: test
      env: Type='mock build'
      language: node_js
      node_js: 8
      script:
        - cd node-libzfs
        - npm pack
        - rename 's/^iml\-//' iml-node-libzfs-*.tgz
        - npm run mock
    - stage: deploy
      env: Type='libzfs-sys'
      language: rust
      rust: stable
      if: branch =~ ^v.+libzfs-sys$
      script:
        - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw intelhpdd/libzfs
        - docker exec -i libzfs bash -c "cd /rust-libzfs/libzfs-sys && cargo package && cargo publish --token $CARGO_TOKEN"
    - stage: deploy
      env: Type='libzfs'
      language: rust
      rust: stable
      if: branch =~ ^v.+\dlibzfs$
      script:
        - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw intelhpdd/libzfs
        - docker exec -i libzfs bash -c "cd /rust-libzfs/libzfs && cargo package && cargo publish --token $CARGO_TOKEN"
    - stage: deploy
      env: Type='@iml/node-libzfs'
      language: node_js
      node_js: 8
      if: branch =~ ^v.+node-libzfs$
      before_deploy:
        - cd node-libzfs
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      env: Type='Fable.Import.NodeLibzfs'
      language: csharp
      dotnet: 2.1.4
      mono: latest
      if: branch =~ ^v.+fable-import-nodelibzfs$
      script:
          - cd Fable.Import.NodeLibzfs
          - dotnet pack
          - cd bin/Debug
          - dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY
    - stage: deploy
      env: Type='bintray master deploy'
      if: branch = master AND env(TRAVIS_TAG) IS blank
      language: node_js
      node_js: 8
      script:
        - cd node-libzfs
        - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
        - RELEASE=$(git rev-list HEAD | wc -l)
        - RPM_NAME=iml-node-libzfs-$PACKAGE_VERSION-*.el7.centos.x86_64.rpm
        - npm pack
        - rename 's/^iml\-//' iml-node-libzfs-*.tgz
        - npm run mock
        - docker exec -ti mock bash -xec "curl -T /var/lib/mock/epel-7-x86_64/result/$RPM_NAME -u$BINTRAY_USER:$BINTRAY_KEY https://api.bintray.com/content/intel-hpdd/intelhpdd-build/iml-node-libzfs/$PACKAGE_VERSION/$RPM_NAME/?publish=1"