sudo: required
services:
  - docker

jobs:
  include:
    - stage: test
      env: Type='bindgen test'
      script:
        - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw intelhpdd/libzfs
        - docker exec -i libzfs bash -c 'cd /rust-libzfs/node-libzfs && cargo build'
        - docker exec -i libzfs bash -c 'cd /rust-libzfs/libzfs-sys && cargo test bindgen_test_layout'
    - stage: test
      env: Type='virus scan'
      script:
        - sudo apt-get install clamav -y
        - sudo freshclam
        - clamscan --quiet -r ./
    - stage: test
      env: Type='ts2fable'
      language: node_js
      node_js: 8
      script:
        - npm i -g ts2fable@0.6.0-build.174
        - ts2fable node-libzfs/types/@iml/node-libzfs/index.d.ts node-libzfs/libzfs.fs
    - stage: test
      env: Type='mock build'
      language: node_js
      node_js: 8
      script:
        - cd node-libzfs
        - npm pack
        - rename 's/^iml\-//' iml-node-libzfs-*.tgz
        - cd ../
        - docker run -dit --privileged --name mock intelhpdd/mock /usr/sbin/init
        - docker cp -a ./ mock:/builddir
        - docker exec -ti mock bash -xec "bash -xe /builddir/node-libzfs/mock-build.sh"
        - PACKAGE_VERSION=$(node -p -e "require('./node-libzfs/package.json').version") && docker exec -ti mock bash -xec "curl -T /var/lib/mock/epel-7-x86_64/result/iml-node-libzfs-$PACKAGE_VERSION-*.el7.centos.x86_64.rpm -u$BINTRAY_USER:$BINTRAY_KEY https://api.bintray.com/content/intel-hpdd/intelhpdd-build/iml-node-libzfs/$PACKAGE_VERSION/;publish=1"
    - stage: deploy
      env: Type='libzfs-sys'
      language: rust
      rust: stable
      if: branch =~ ^v.+libzfs-sys$
      script:
        - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw intelhpdd/libzfs
        - docker exec -i libzfs bash -c "cd /rust-libzfs/libzfs-sys && cargo package && cargo publish --token $CARGO_TOKEN"
    - stage: deploy
      env: Type='libzfs'
      language: rust
      rust: stable
      if: branch =~ ^v.+\dlibzfs$
      script:
        - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw intelhpdd/libzfs
        - docker exec -i libzfs bash -c "cd /rust-libzfs/libzfs && cargo package && cargo publish --token $CARGO_TOKEN"
    - stage: deploy
      env: Type='@iml/node-libzfs'
      language: node_js
      node_js: 8
      if: branch =~ ^v.+node-libzfs$
      before_deploy:
        - npm i -g ts2fable@0.6.0-build.174
        - ts2fable node-libzfs/types/@iml/node-libzfs/index.d.ts node-libzfs/libzfs.fs
        - cd node-libzfs
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
