sudo: required
language: generic
services:
    - docker
jobs:
    include:
        - stage: test
          name: "bindgen test"
          script:
              - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw imlteam/zfs
              - docker exec -i libzfs bash -c 'cd /rust-libzfs/node-libzfs && cargo build'
              - docker exec -i libzfs bash -c 'cd /rust-libzfs/libzfs-sys && cargo test bindgen_test_layout'
        - stage: test
          name: "mock build"
          language: node_js
          node_js: "10"
          script:
              - cd node-libzfs
              - npm run mock
        - stage: deploy-libzfs-sys
          name: "libzfs-sys"
          script:
              - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw imlteam/zfs
              - docker exec -i libzfs bash -c "cd /rust-libzfs/libzfs-sys && cargo package && cargo publish --token $CARGO_TOKEN"
        - stage: deploy-libzfs
          name: "libzfs"
          script:
              - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw imlteam/zfs
              - docker exec -i libzfs bash -c "cd /rust-libzfs/libzfs && cargo package && cargo publish --token $CARGO_TOKEN"
        - stage: deploy-libzfs-types
          name: "libzfs-types"
          script:
              - docker run -d -it --name libzfs -v $(pwd):/rust-libzfs:rw imlteam/zfs
              - docker exec -i libzfs bash -c "cd /rust-libzfs/libzfs-types && cargo package && cargo publish --token $CARGO_TOKEN"
        - stage: deploy-node-libzfs
          name: "@iml/node-libzfs"
          language: node_js
          node_js: "10"
          before_deploy:
              - cd node-libzfs
          deploy:
              provider: npm
              email: "$NPM_EMAIL"
              api_key: "$NPM_TOKEN"
              skip_cleanup: true
              on:
                  tags: true
        - stage: deploy-copr
          name: "Copr deploy"
          before_deploy:
              - include/travis/copr-deploy.sh prepare
          deploy:
              skip_cleanup: true
              provider: script
              script: ./travis_wait "./include/travis/run_in_centos7_docker.sh ./include/travis/copr-deploy.sh build"
              on:
                  all_branches: true
stages:
    - test
    - name: deploy-libzfs-sys
      if: branch =~ ^v\d+\.\d+\.\d+libzfs-sys$
    - name: deploy-libzfs
      if: branch =~ ^v\d+\.\d+\.\d+libzfs$
    - name: deploy-libzfs-types
      if: branch =~ ^v\d+\.\d+\.\d+libzfs-types$
    - name: deploy-node-libzfs
      if: branch =~ ^v\d+\.\d+\.\d+node-libzfs$
    - name: deploy-copr
      if: branch =~ ^v\d+\.\d+\.\d+-.+node-libzfs$
